//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.05 at 02:05:01 PM FET 
//


package by.epam.lab.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Dosage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Dosage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Dose" type="{http://xml.netbeans.org/schema/MedicineSchema}dose"/>
 *         &lt;element name="Reception" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Dosage", propOrder = {
    "dose",
    "reception"
})
public class Dosage {

    @XmlElement(name = "Dose")
    protected float dose;
    @XmlElement(name = "Reception", required = true)
    protected String reception;

    /**
     * Gets the value of the dose property.
     * 
     */
    public float getDose() {
        return dose;
    }

    /**
     * Sets the value of the dose property.
     * 
     */
    public void setDose(float value) {
        this.dose = value;
    }

    /**
     * Gets the value of the reception property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReception() {
        return reception;
    }

    /**
     * Sets the value of the reception property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReception(String value) {
        this.reception = value;
    }

}
