//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.05 at 02:05:01 PM FET 
//


package by.epam.lab.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MedGroup.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MedGroup">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="антибиотики"/>
 *     &lt;enumeration value="жаропонижающие"/>
 *     &lt;enumeration value="болеутоляющие"/>
 *     &lt;enumeration value="витамины"/>
 *     &lt;enumeration value="адсорбирующие"/>
 *     &lt;enumeration value="антидипресанты"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MedGroup")
@XmlEnum
public enum MedGroup {

    @XmlEnumValue("\u0430\u043d\u0442\u0438\u0431\u0438\u043e\u0442\u0438\u043a\u0438")
    антибиотики("\u0430\u043d\u0442\u0438\u0431\u0438\u043e\u0442\u0438\u043a\u0438"),
    @XmlEnumValue("\u0436\u0430\u0440\u043e\u043f\u043e\u043d\u0438\u0436\u0430\u044e\u0449\u0438\u0435")
    жаропонижающие("\u0436\u0430\u0440\u043e\u043f\u043e\u043d\u0438\u0436\u0430\u044e\u0449\u0438\u0435"),
    @XmlEnumValue("\u0431\u043e\u043b\u0435\u0443\u0442\u043e\u043b\u044f\u044e\u0449\u0438\u0435")
    болеутоляющие("\u0431\u043e\u043b\u0435\u0443\u0442\u043e\u043b\u044f\u044e\u0449\u0438\u0435"),
    @XmlEnumValue("\u0432\u0438\u0442\u0430\u043c\u0438\u043d\u044b")
    витамины("\u0432\u0438\u0442\u0430\u043c\u0438\u043d\u044b"),
    @XmlEnumValue("\u0430\u0434\u0441\u043e\u0440\u0431\u0438\u0440\u0443\u044e\u0449\u0438\u0435")
    адсорбирующие("\u0430\u0434\u0441\u043e\u0440\u0431\u0438\u0440\u0443\u044e\u0449\u0438\u0435"),
    @XmlEnumValue("\u0430\u043d\u0442\u0438\u0434\u0438\u043f\u0440\u0435\u0441\u0430\u043d\u0442\u044b")
    антидипресанты("\u0430\u043d\u0442\u0438\u0434\u0438\u043f\u0440\u0435\u0441\u0430\u043d\u0442\u044b");
    private final String value;

    MedGroup(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MedGroup fromValue(String v) {
        for (MedGroup c: MedGroup.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
